# Generated by Django 5.1 on 2024-08-09 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='quran/author/images/')),
                ('age', models.CharField(max_length=100)),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authorlar',
            },
        ),
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_oyat', models.IntegerField(default=0)),
                ('lang', models.CharField(choices=[('english', 'English'), ('uzbek', 'Uzbek'), ('russian', 'Russian'), ('arabic', 'Arabic')], max_length=45)),
                ('written_place', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Sura',
                'verbose_name_plural': 'Suralar',
            },
        ),
        migrations.CreateModel(
            name='Oyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('english', 'English'), ('uzbek', 'Uzbek'), ('russian', 'Russian'), ('arabic', 'Arabic')], max_length=45)),
                ('oyat_number', models.BigIntegerField(default=0)),
                ('translate', models.TextField(default='Tarjimasi')),
                ('audio', models.FileField(upload_to='quran/audios/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.author')),
                ('sura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oyatlar', to='quran.sura')),
            ],
            options={
                'verbose_name': 'Oyat',
                'verbose_name_plural': 'Oyatlar',
            },
        ),
    ]
