# Generated by Django 5.1 on 2024-08-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Quran', max_length=150)),
                ('pdf', models.FileField(upload_to='quran/books/')),
                ('lang', models.CharField(blank=True, choices=[('en', 'English'), ('uz', 'Uzbek'), ('ru', 'Russian'), ('ar', 'Arabic')], max_length=35, null=True)),
                ('online_read', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Quran',
                'verbose_name_plural': 'Quran',
            },
        ),
    ]
